SET IDENTITY_INSERT [dbo].[Teams] ON
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2201, N'FCB', N'barcelona', N'~/Content/imgs/FCB.png', 2040)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2202, N'R.Madrid', N'madrid', N'~/Content/imgs/R.Madrid.png', 2040)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2203, N'PSG', N'south france', N'~/Content/imgs/PSG.png', 2040)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2204, N'Byern', N'munich', N'~/Content/imgs/Byern.png', 2039)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2205, N'Bvb', N'munich', N'~/Content/imgs/Bvb.png', 2040)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2206, N'Arsenal', N'museryside', N'~/Content/imgs/Arsenal.png', 2039)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2207, N'Deportivo', N'barcelona', N'~/Content/imgs/Deportivo.png', 2040)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2208, N'ACMilan', N'milan', N'~/Content/imgs/ACMilan.png', 2038)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2209, N'Inter', N'milan', N'~/Content/imgs/Inter.png', 2040)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2210, N'FCPorto', N'portugal', N'~/Content/imgs/FCPorto.png', 2040)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2211, N'Monaco', N'monaco', N'~/Content/imgs/Monaco.png', NULL)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2212, N'Spurs', N'museryside', N'~/Content/imgs/Spurs.png', NULL)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2213, N'Galetasery', N' istambul', N'~/Content/imgs/Galetasery.png', NULL)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2214, N'ASRoma', N'rome', N'~/Content/imgs/Roma.png', 2040)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2215, N'ManU', N'london', N'~/Content/imgs/ManU.png', 2039)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2216, N'ManCity', N'london', N'~/Content/imgs/ManCity.png', 2039)
INSERT INTO [dbo].[Teams] ([id], [name], [kasi], [imgPath], [Tournament_id]) VALUES (2217, N'NewTeam', N'NewHamsher', N'~/Content/imgs/NewTeam182340734.jpg', NULL)
SET IDENTITY_INSERT [dbo].[Teams] OFF
